name: nodelabelbot5000
version: 0.1.0
description: The Cluster Manager API Operator
keywords:
- hybridstack
- api
home: https://github.com/samsung-cnct/nodelabelbot5000
sources:
- https://github.com/samsung-cnct/nodelabelbot5000
maintainers:
- name: Samsung CNCT
  email: samsung.cloudnative@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
